language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install pipenv --upgrade
  - pipenv install --dev --skip-lock
# command to run tests
cache: pip
script:
  - pipenv install -e .
  - pipenv run python -m  unittest discover # or py.test for Python versions 3.5 and below